language: node_js
node_js:
  - "6"

before_script:
  - npm install

script:
  - npm run lint
  - npm run test

before_deploy:
  - cat package.json

deploy:
  provider: npm
  api_key: "$NPM_API_KEY"
  email: nick@nickwhyte.com
  on:
    tags: true
